blank_issues_enabled: false
contact_links:
  - name: pyOpenSci Documentation
    url: https://www.pyopensci.org/software-peer-review/how-to/onboarding-guide.html
    about: Please check our documentation for general information about pyOpenSci.
